name: Website CD
# some changes: 1,
on:
  
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-north-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: 685631290880.dkr.ecr.eu-north-1.amazonaws.com/dw/caddy  # set this to your Amazon ECR repository name
  # CONTAINER_NAME: MY_CONTAINER_NAME           set this to the name of the container in the
                                               # containerDefinitions section of your task definition
  PR_NUMBER: ${{ github.event.number }}
  SSH_KEY: ${{ secrets.PASS_KEY_VALUE }}
  HOSTNAME: ${{secrets.DEV_IP}}
  PROD_HOSTNAME: ${{secrets.PROD_IP}}
  USER_NAME: ${{secrets.USER_NAME}}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install ansible
      run: |
        sudo apt-get install -y ansible

    - name: Create merge tag
      run: |
        TAG="merge-$(date +'%Y%m%d-%H%M%S')"
        echo "TAG=$TAG" >> $GITHUB_ENV


    - name: Build & Integrate
      run: |
        echo "$SSH_KEY" > ssh_key && chmod 600 ssh_key
        ssh -o StrictHostKeyChecking=no -i ssh_key "${USER_NAME}@${HOSTNAME}" "
          cd roni-s-website
          docker build -t mycaddy:${{ env.TAG }} -f CaddyDockerfile --build-arg Caddyfile=testCaddyfile . &&
          docker run -d -p 80:80 -p 443:443 -v caddy_data:/data mycaddy:${{ env.TAG }}
          "
    - name: my Tests
      run: |
        curl -Lv dev.fruhling-bakery.com
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_NAME: dw/caddy
        IMAGE_TAG: ${{ env.PR_NUMBER }}

      run: |
        # Build the image
        docker build -t $IMAGE_NAME:latest -f CaddyDockerfile --build-arg Caddyfile=Caddyfile .

        # Tag it for ECR
        docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest

        # Push to ECR
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Add SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ env.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ env.PROD_HOSTNAME }}" >> ~/.ssh/known_hosts

    - name: Setting up prod server
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ansible-playbook -i inventory.ini playbook.yml 
   
    - name: continuos delivery
      run: |
        ssh -o StrictHostKeyChecking=no -i ssh_key "${USER_NAME}@${PROD_HOSTNAME}" "
          docker stop \\$(docker ps -q) || true &&
          docker run -d -p 80:80 -p 443:443 -v caddy_data:/data $i{{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          "

        
  post-tasks:
    name: Cleanup Dev Server
    runs-on: ubuntu-latest
    needs: deploy             # ðŸ‘ˆ depends on the previous job
    if: always()              # ðŸ‘ˆ runs even if deploy failed
    steps:
    - name: Build & Integrate
      run: |
        echo "$SSH_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key "${USER_NAME}@${HOSTNAME}" 'docker stop $(docker ps -aq)'
        # echo "caddy container is runing"
