name: Website CI
# some changes: 1,
on:
  
  push:
    branches: [ dev ]

env:
  AWS_REGION: eu-north-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: 685631290880.dkr.ecr.eu-north-1.amazonaws.com/dw/caddy  # set this to your Amazon ECR repository name
  # CONTAINER_NAME: MY_CONTAINER_NAME           set this to the name of the container in the
                                               # containerDefinitions section of your task definition
  PR_NUMBER: ${{ github.event.number }}
  PRIVATE_KEY: ${{ secrets.PASS_KEY_VALUE }}
  HOSTNAME: ${{secrets.DEV_IP}}
  PROD_HOSTNAME: ${{secrets.PROD_IP}}
  USER_NAME: ${{secrets.USER_NAME}}

permissions:
  contents: read

jobs:
  continous-integration:
    name: setup environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build & Integrate
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key "${USER_NAME}@${HOSTNAME}" "
          cd roni-s-website
          git pull
          docker-compose down
          docker-compose up -d --build
          "
    - name: Debug Connectivity
      run: |
        echo "--- DNS ---"
        dig dev.fruhling-bakery.com
        echo "--- HTTP ---"
        curl -v http://dev.fruhling-bakery.com || true
        echo "--- HTTPS ---"
        curl -v https://dev.fruhling-bakery.com || true

    - name: my Tests
      run: |
        curl -Lv dev.fruhling-bakery.com
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1

    - name: debugging docker compose installation
      run: |
        which docker-compose
        dcoker-compose

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_WEB_NAME: dw/roni-s-website-web
        IMAGE_CADDY_NAME: dw/roni-s-website-caddy
        IMAGE_TAG: v1.0.${{ env.PR_NUMBER }}

      run: |
        # Build the image
        docker-compose build

        # Tag it for ECR
        docker tag $IMAGE_WEB_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_WEB_NAME:$IMAGE_TAG
        docker tag $IMAGE_CADDY_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_CADDY_NAME:$IMAGE_TAG
        # Push to ECR
        docker push $ECR_REGISTRY/$IMAGE_WEB_NAME:$IMAGE_TAG
        docker push $ECR_REGISTRY/$IMAGE_CADDY_NAME:$IMAGE_TAG
  post-tasks:
    name: Cleanup Dev Server
    runs-on: ubuntu-latest
    needs: continous-integration             # ðŸ‘ˆ depends on the previous job
    if: always()              # ðŸ‘ˆ runs even if deploy failed
    steps:
    - name: Build & Integrate
      run: |
        echo "nice"
        # echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        # ssh -o StrictHostKeyChecking=no -i private_key "${USER_NAME}@${HOSTNAME}" 'docker stop $(docker ps -aq)'
        # echo "caddy container is runing"
