name: Website CI
# some changes: 1,
on:
  
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: 685631290880.dkr.ecr.eu-north-1.amazonaws.com/dw/caddy  # set this to your Amazon ECR repository name
  # CONTAINER_NAME: MY_CONTAINER_NAME           set this to the name of the container in the
                                               # containerDefinitions section of your task definition
  PR_NUMBER: ${{ github.event.number }}
  PRIVATE_KEY: ${{ secrets.PASS_KEY_VALUE }}
  HOSTNAME: ${{secrets.DEV_IP}}
  PROD_HOSTNAME: ${{secrets.PROD_IP}}
  USER_NAME: ${{secrets.USER_NAME}}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build & Integrate
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key "${USER_NAME}@${HOSTNAME}" "
          cd roni-s-website
          docker build -t mycaddy/${{ env.PR_NUMBER }} -f CaddyDockerfile --build-arg Caddyfile=testCaddyfile . &&
          docker run -d -p 80:80 -p 443:443 --volume=/home/caddy:/var/lib/caddy mycaddy/${{ env.PR_NUMBER }}
          "
    - name: my Tests
      run: |
        curl -Lv test.fruhling-bakery.com
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: dw/caddy:${{ env.PR_NUMBER }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t ${{ env.IMAGE_TAG }} -f CaddyDockerfile --build-arg Caddyfile=testCaddyfile .
        docker tag ${{ env.IMAGE_TAG }} 685631290880.dkr.ecr.eu-north-1.amazonaws.com/${{ env.IMAGE_TAG }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  post-tasks:
    name: Cleanup Dev Server
    runs-on: ubuntu-latest
    needs: deploy             # ðŸ‘ˆ depends on the previous job
    if: always()              # ðŸ‘ˆ runs even if deploy failed
    steps:
    - name: Build & Integrate
      run: |
       # echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        #ssh -o StrictHostKeyChecking=no -i private_key "${USER_NAME}@${HOSTNAME}" 'docker stop $(docker ps -aq)'
        echo "caddy container is runing"
